openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: CPE Chatbot API Description
  contact:
    name: Mike
servers:
  - url: 'https://awrchatbot.org/api'
    description: Live System
  - url: 'https://cpe.toak.de/api'
    description: Test System
paths:
  /auth:
    post:
      summary: login
      tags: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
      operationId: post-auth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                idtoken:
                  type: string
      parameters: []
      description: get authentication token
  /evangelists:
    get:
      summary: search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email:
                    type: string
                  cellphone:
                    type: string
                  teachercode:
                    type: array
                    items:
                      type: string
              examples: {}
      operationId: get-evangelists
      security:
        - idtoken: []
      parameters:
        - schema:
            type: string
          in: query
          name: firstname
        - schema:
            type: string
          in: query
          name: lastname
        - schema:
            type: string
          in: query
          name: email
        - schema:
            type: string
          in: query
          name: cellphone
      description: search for evangelists
  '/evangelists/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  firstname:
                    type: string
                  lastname:
                    type: string
                  email:
                    type: string
                  cellphone:
                    type: string
                  teachercode:
                    type: array
                    items:
                      type: string
      operationId: get-evangelists-id
      security:
        - idtoken: []
      description: get full evangelist details
    put:
      summary: edit
      tags: []
      responses:
        '200':
          description: OK
      operationId: put-evangelists-id
      security:
        - idtoken: []
      description: edit evangelist
    delete:
      summary: remove
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-evangelists-id
      security:
        - idtoken: []
      description: delete evanglist
components:
  schemas: {}
  securitySchemes:
    idtoken:
      name: Google Sign in
      type: apiKey
      in: query
security:
  - undefined: []
tags: []
